apiVersion: sources.triggermesh.io/v1alpha1
kind: HTTPPollerSource
metadata:
  name: test-http-poller
  namespace: knative-eventing
spec:
  eventType: weather.alerts/kansas
  eventSource: gov.weather
  endpoint: https://api.weather.gov/alerts/active?area=KS
  method: GET
  interval: 20s
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
