apiVersion: sources.triggermesh.io/v1alpha1
kind: IBMMQSource
metadata:
  name: ibm-mq-source
  namespace: knative-eventing
spec:
  connectionName: ibm-mq.knative-eventing.svc.cluster.local(1414)
  queueManager: QM1
  queueName: DEV.QUEUE.1
  channelName: DEV.APP.SVRCONN
  delivery:
    deadLetterQueue: DEV.DEAD.LETTER.QUEUE
    retry: 3
  credentials:
    username:
      valueFromSecret:
        name: ibm-mq-secret
        key: username
    password:
      valueFromSecret:
        name: ibm-mq-secret
        key: password
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
---
apiVersion: v1
kind: Secret
metadata:
  name: ibm-mq-secret
  namespace: knative-eventing
data:
  username: YXBw
  password: cGFzc3dvcmQ=
type: Opaque