apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: knative-serving

resources:
  - knative-serving/serving-crds.yaml
  - knative-serving/serving-core.yaml
  - knative-serving/serving-hpa.yaml
  - knative-serving/serving-default-domain.yaml