apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: test-pingsource
  namespace: knative-eventing
spec:
  schedule: "*/1 * * * *"
  contentType: "application/json"
  data: '{ "message" : "hello" }'
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default