apiVersion: v1
kind: ServiceAccount
metadata:
  name: gtflp
  namespace: knative-eventing
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gtflp
  namespace: knative-eventing
rules:
  - apiGroups:
      - serving.knative.dev
      - metrics.k8s.io
      - extensions
      - apps
      - eventing.knative.dev
      - ""
      - flow.triggermesh.io
      - sources.triggermesh.io
    resources:
      - pods/log
      - events
      - nodes
      - pods
      - deployments
      - replicasets
      - routes
      - brokers
      - triggers
      - bridges
      - azureactivitylogssources
      - azureblobstoragesources
      - azureeventgridsources
      - azureeventhubsources
      - azurequeuestoragesources
      - googlecloudauditlogssources
      - googlecloudbillingsources
      - googlecloudpubsubsources
      - googlecloudstoragesources
      - ocimetricssources
      - salesforcesources
      - twiliosources
      - httppollersources
      - slacksources
      - webhooksources
      - zendesksources
      - awscloudwatchlogssources
      - awscloudwatchsources
      - awscodecommitsources
      - awscognitoidentitysources
      - awscognitouserpoolsources
      - awsdynamodbsources
      - awskinesissources
      - awsperformanceinsightssources
      - awss3sources
      - awssnssources
      - awssqssources
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gtflp
  namespace: knative-eventing
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gtflp
subjects:
  - kind: ServiceAccount
    name: gtflp
    # UPDATE THIS TO MATCH YOUR NAMESPACE:
    namespace: knative-eventing
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: gtflp
  namespace: knative-eventing
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: gtflp
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gtflp
  namespace: knative-eventing
spec:
  template:
    spec:
      serviceAccountName: gtflp
      containers:
        - image: tmjeff/gtflp-74a7bfcfca304ccc24ab0c1018431452
          env:
---
